### ISSUE TITLE
Создать и реализовать `processSectionCallback(CallbackQuery callback)`

### ISSUE THREAD

**Issue by YawKar** [Haermeus-DevGroup/haermeus-bot#10]
Делать после #9 

- [x] Создать в боте метод:
```java
private void processSectionCallback(CallbackQuery callback) {}
```
- [x] Сначала получить номер секции из данных колбека
```java
var sectionId = Long.parseLong(callback.getData().split(" ")[1]);
```
- [x] Создать переменную для будущего ответного действия, изменяющего сообщение с открытым меню
```java
EditMessageText response;
```
- [x] Если `sectionId == -1` (означает, что запрашиваемая секция является корнем всего каталога), создаём ответный запрос на изменение сообщения. Не обращай внимание на вызов метода `makeRootsInlineKeyboardMarkup(sectionsApi.getRootSections())`, он будет реализован в другой задаче
```java
if (sectionId == -1) {
    response = EditMessageText.builder()
            .chatId(callback.getMessage().getChatId())
            .messageId(callback.getMessage().getMessageId())
            .inlineMessageId(callback.getInlineMessageId())
            .text("Корневой каталог")
            .replyMarkup(makeRootsInlineKeyboardMarkup(sectionsApi.getRootSections()))
            .build();
} 
```
- [x] Иначе если `sectionId` не равен -1, мы делаем запрос на бекенд, чтобы получить конкретную секцию и её детей (подсекции либо ресурсы). Не обращай внимание на вызов `makeSectionInlineKeyboardMarkup(section, childSections, childResources)`, мы реализуем его в другой задаче.
```java
else {
    var section = sectionsApi.getPlainSection(sectionId);
    var childSections = sectionsApi.getChildrenSections(sectionId);
    var childResources = sectionsApi.getChildrenResources(sectionId);
    response = EditMessageText.builder()
            .chatId(callback.getMessage().getChatId())
            .messageId(callback.getMessage().getMessageId())
            .inlineMessageId(callback.getInlineMessageId())
            .text(section.getTitle())
            .replyMarkup(makeSectionInlineKeyboardMarkup(section, childSections, childResources))
            .build();
}
```
- [x] В конце вставляем `try/catch` блок
  - [x] В `try{..}` мы сначала выполняем запрос на изменение меню: `execute(response);`, а затем помечаем CallbackQuery как выполненный: `execute(new AnswerCallbackQuery(callback.getId()));`
  - [x] В `catch(..)` мы должны ловить `TelegramApiException e` и логировать ошибку: `log.error("Cannot process section callback {}", callback, e);`

**Comment by RandomName-proj** [comment]
сделал в 6e3c4b9e937547be0ee5ca999e1029b7a9d804e6
