### ISSUE TITLE
Создать и реализовать `processResourceCallback(CallbackQuery callback)`

### ISSUE THREAD

**Issue by YawKar** [Haermeus-DevGroup/haermeus-bot#11]
Делать после #9 

- [x] Создать в боте метод:
```java
private void processResourceCallback(CallbackQuery callback) {}
```
- [x] Сначала получить номер ресурса из данных коллбека
```java
var resourceId = Long.parseLong(callback.getData().split(" ")[1]);
```
- [x] Сделать запрос на бекенд и получить полную версию ресурса с контентом
```java
var resource = resourcesApi.getFullResource(resourceId);
```
- [x] Собрать запрос на изменение сообщения с меню с помощью билдера. Не обращай внимание на вызов метода `makeBackButtonInlineKeyboardMarkup("section " + resource.getParentId().toString())`, мы реализуем его в другой задаче
```java
var response = EditMessageText.builder()
        .chatId(callback.getMessage().getChatId())
        .messageId(callback.getMessage().getMessageId())
        .inlineMessageId(callback.getInlineMessageId())
        .text(resource.getContent())
        .replyMarkup(makeBackButtonInlineKeyboardMarkup("section " + resource.getParentId().toString()))
        .build();
```
- [x] В конце вставляем `try/catch` блок
  - [x] В `try{..}` мы сначала выполняем запрос на изменение меню: `execute(response);`, а затем помечаем CallbackQuery как выполненный: `execute(new AnswerCallbackQuery(callback.getId()));`
  - [x] В `catch(..)` мы должны ловить `TelegramApiException e` и логировать ошибку: `log.error("Cannot process resource callback {}", callback, e);`

**Comment by RandomName-proj** [comment]
сделал в 8f3c410a3540b4811e7a37bfecb760de2ef1118c
