### ISSUE TITLE
Добавить эмодзи категории и статьи

### ISSUE THREAD

**Issue by YawKar** [Haermeus-DevGroup/haermeus-bot#32]
## Создать класс форматтера
- [x] Создать класс `dev.haermeus.haermeusbot.service.HeadingsFormatterService`
- [x] Сделать приватным его дефолтный конструктор
- [x] Добавить поля с эмодзи:
  - [x] `private static final String DIRECTORY_EMOJI = "\uD83D\uDCC2"; //📂`
  - [x] `private static final String OPEN_BOOK_EMOJI = "\uD83D\uDCD6"; //📖`
  - [x] `private static final String BACK_ARROW_EMOJI = "\uD83D\uDD19"; //🔙`
  - [x] `private static final String FORMATTED_TEMPLATE = "%s %s";`
- [x] Реализовать методы, которые просто будут форматировать `FORMATTED_TEMPLATE`, подставляя заголовок ресурса/секции и соответствующий эмодзи:
  - [x] Используйте `.formatted()` метод строк для подстановки в `FORMATTED_TEMPLATE`, результат должен быть такой: "📂 Название какой-то категории", "📖 Название какого-то ресурса", "🔙 Кнопка вернуться"
  - [x] `public static String formatResourceTitle(String title)`
  - [x] `public static String formatSectionTitle(String title)`
  - [x] `public static String formatBackTitle(String title)`

## Обновить `HaermeusBot`
- [x] Добавьте статическое импортирование всех методов класса форматтера через звездочку
- [x] Добавьте вызовы форматирования в методы класса `HaermeusBot`
  - [x] В методе `processMessage` оберните название корневого каталога в вызов `formatSectionTitle(..)`
  - [x] В методе `processSectionCallback` оберните название корневого каталога в вызов `formatSectionTitle(..)`
  - [x] В этом же методе чуть ниже оберните в этот же вызов заголовок секции при формировании ответа (`response`)

## Обновить `MakerService`
- [x] Добавьте статическое импортирование всех методов класса форматтера через звездочку
- [x] Добавьте вызовы форматирования в методы класса `MakerService`
  - [x] В методе `makeInlineKeyboardButton(PlainSectionDTO section)` оберните заголовок секции в вызов `formatSectionTitle(..)`
  - [x] В методе `makeInlineKeyboardButton(PlainResourceDTO resource)` оберните заголовок секции в вызов `formatResourceTitle(..)`
  - [x] В методе `makeBackButton(String callbackData)` оберните "Вернуться" в вызов `formatBackTitle(..)`
  - [x] В методе `makeRootsInlineKeyboardMarkup(List<PlainSectionDTO> plainSections)` оберните заголовки секций в вызов `formatSectionTitle(..)`

**Comment by RandomName-proj** [comment]
сделано в 64b344a9ce4fbf033e736d8a2c83607031dd9e9e
