### ISSUE TITLE
Реализовать `processMessage(Update update)`

### ISSUE THREAD

**Issue by YawKar** [Haermeus-DevGroup/haermeus-bot#8]
Делать после #7

- [x] В начале метода логировать `log.info("Start processing message {}", update.getMessage());`
- [x] Создать `try/catch` блок
  - [x] Он должен иметь блок `catch (TelegramApiException e)`, в котором логировать ошибку `log.error("Cannot process message {}", update, e);`
  - [x] В `try {..}` надо воспользоваться builder'ом объекта `SendMessage`, как приведено ниже. Не обращай внимание на вызов `makeRootsInlineKeyboardMarkup(sectionsApi.getRootSections())`, потом реализуем в другой задаче 

```java
var response = SendMessage.builder()
                    .chatId(update.getMessage().getChatId())
                    .text("Корневой каталог")
                    .replyMarkup(makeRootsInlineKeyboardMarkup(sectionsApi.getRootSections()))
                    .build();
```
- [x] В конце `try {..}` блока добавь выполнение запроса на отправку сообщения:
```java
execute(response);
```

**Comment by RandomName-proj** [comment]
сделано в d713d1e75fa3b7ef0d43de032dd4bfda4b008a31
