### ISSUE TITLE
Реализовать `processCallbackQuery(Update update)`

### ISSUE THREAD

**Issue by YawKar** [Haermeus-DevGroup/haermeus-bot#9]
Делать после #7 

- [x] В начале метода логировать 
```java
log.info("Start processing callback query {}", update.getCallbackQuery());
```
- [x] Затем вытащить для удобства объект обратного вызова
```java
CallbackQuery callback = update.getCallbackQuery();
```
- [x] Если `callback.getData()` начинается с `"section"`, вызываем метод ниже. Не обращай внимание, что он пока что не создан, создадим в другой задаче.
```java
processSectionCallback(callback);
```
- [x] Иначе если `callback.getData()` начинается с `"resource"`, вызываем метод ниже. Опять-таки не обращай внимание на то, что метод ещё не создан, создадим в другой задаче.
```java
processResourceCallback(callback);
```
- [x] Иначе, если `callback.getData()` не начинается с `"resource"` или `"section"`, логируем ошибку
```java
log.error("Unknown callback {}", callback);
```

**Comment by RandomName-proj** [comment]
сделано в bcbcd5ff464fb9f933c95a7fadae160f71985b1b
